/* Generated by Yosys 0.25+99 (git sha1 54bf15a5b, x86_64-apple-darwin20.2-clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* top =  1  *)
(* src = "FA_DR.v:5.1-66.10" *)
module toplevel(clk, rst, cin_n, cin_p, x_n, x_p, y_n, y_p, cout_n, cout_p, sum_n, sum_p);
  (* src = "FA_DR.v:8.11-8.16" *)
  wire _00_;
  (* src = "FA_DR.v:9.11-9.16" *)
  wire _01_;
  (* src = "FA_DR.v:14.12-14.18" *)
  wire _02_;
  (* src = "FA_DR.v:15.12-15.18" *)
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  (* src = "FA_DR.v:16.12-16.17" *)
  wire _24_;
  (* src = "FA_DR.v:17.12-17.17" *)
  wire _25_;
  (* src = "FA_DR.v:10.11-10.14" *)
  wire _26_;
  (* src = "FA_DR.v:11.11-11.14" *)
  wire _27_;
  (* src = "FA_DR.v:12.11-12.14" *)
  wire _28_;
  (* src = "FA_DR.v:13.11-13.14" *)
  wire _29_;
  (* src = "FA_DR.v:8.11-8.16" *)
  input cin_n;
  wire cin_n;
  (* src = "FA_DR.v:9.11-9.16" *)
  input cin_p;
  wire cin_p;
  (* src = "FA_DR.v:6.11-6.14" *)
  input clk;
  wire clk;
  (* src = "FA_DR.v:14.12-14.18" *)
  output cout_n;
  wire cout_n;
  (* src = "FA_DR.v:15.12-15.18" *)
  output cout_p;
  wire cout_p;
  (* src = "FA_DR.v:7.11-7.14" *)
  input rst;
  wire rst;
  (* src = "FA_DR.v:16.12-16.17" *)
  output sum_n;
  wire sum_n;
  (* src = "FA_DR.v:17.12-17.17" *)
  output sum_p;
  wire sum_p;
  (* src = "FA_DR.v:19.10-19.15" *)
  wire tmp34;
  (* src = "FA_DR.v:20.10-20.15" *)
  wire tmp36;
  (* src = "FA_DR.v:21.10-21.15" *)
  wire tmp39;
  (* src = "FA_DR.v:22.10-22.15" *)
  wire tmp41;
  (* src = "FA_DR.v:23.10-23.15" *)
  wire tmp42;
  (* src = "FA_DR.v:24.10-24.15" *)
  wire tmp43;
  (* src = "FA_DR.v:25.10-25.15" *)
  wire tmp44;
  (* src = "FA_DR.v:26.10-26.15" *)
  wire tmp45;
  (* src = "FA_DR.v:27.10-27.15" *)
  wire tmp46;
  (* src = "FA_DR.v:28.10-28.15" *)
  wire tmp47;
  (* src = "FA_DR.v:29.10-29.15" *)
  wire tmp48;
  (* src = "FA_DR.v:30.10-30.15" *)
  wire tmp50;
  (* src = "FA_DR.v:31.10-31.15" *)
  wire tmp51;
  (* src = "FA_DR.v:32.10-32.15" *)
  wire tmp52;
  (* src = "FA_DR.v:33.10-33.15" *)
  wire tmp53;
  (* src = "FA_DR.v:34.10-34.15" *)
  wire tmp56;
  (* src = "FA_DR.v:35.10-35.15" *)
  wire tmp57;
  (* src = "FA_DR.v:36.10-36.15" *)
  wire tmp59;
  (* src = "FA_DR.v:37.10-37.15" *)
  wire tmp60;
  (* src = "FA_DR.v:38.10-38.15" *)
  wire tmp61;
  (* src = "FA_DR.v:10.11-10.14" *)
  input x_n;
  wire x_n;
  (* src = "FA_DR.v:11.11-11.14" *)
  input x_p;
  wire x_p;
  (* src = "FA_DR.v:12.11-12.14" *)
  input y_n;
  wire y_n;
  (* src = "FA_DR.v:13.11-13.14" *)
  input y_p;
  wire y_p;
  assign _04_ = ~_27_;
  assign _05_ = ~_29_;
  assign _06_ = ~_01_;
  assign _07_ = ~_28_;
  assign _08_ = ~_26_;
  assign _09_ = ~(_07_ & _08_);
  assign _10_ = ~(_28_ & _26_);
  assign _11_ = ~(_00_ & _09_);
  assign _02_ = ~(_10_ & _11_);
  assign _12_ = ~(_27_ & _29_);
  assign _13_ = ~(_06_ & _12_);
  assign _14_ = ~(_04_ & _05_);
  assign _15_ = ~(_13_ & _14_);
  assign _03_ = ~_15_;
  assign _16_ = ~(_10_ & _12_);
  assign _17_ = ~(_01_ & _16_);
  assign _18_ = ~(_29_ & _26_);
  assign _19_ = ~(_27_ & _28_);
  assign _20_ = ~(_18_ & _19_);
  assign _21_ = ~(_00_ & _20_);
  assign _25_ = ~(_17_ & _21_);
  assign _22_ = ~(_01_ & _20_);
  assign _23_ = ~(_00_ & _16_);
  assign _24_ = ~(_22_ & _23_);
  assign tmp39 = cout_n;
  assign tmp42 = cout_p;
  assign tmp48 = sum_p;
  assign tmp50 = sum_n;
  assign cout_n = _02_;
  assign _27_ = x_p;
  assign _29_ = y_p;
  assign cout_p = _03_;
  assign _01_ = cin_p;
  assign _00_ = cin_n;
  assign sum_p = _25_;
  assign sum_n = _24_;
  assign _28_ = y_n;
  assign _26_ = x_n;
endmodule
